name: mooShape
author: remram
category: Interface
tags: [widgets,interface,shape,canvas,html5]
docs: https://github.com/remram/ch.remram.mootools.mooShape/blob/master/README.md
demo: http://jsfiddle.net/remram/UkDTE/
current: 1.0